/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test4;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvFileSource;

import static org.junit.jupiter.api.Assertions.*;

class test4Test {
    @ParameterizedTest
    @DisplayName("决策表分析方法测试")
    @CsvFileSource(resources= "/test4.csv")
    void fileTest1(String fromTime,String toTime,String expected){
        test4 phoneFee=new test4();
        assertEquals(expected,phoneFee.GetMoney(fromTime,toTime));
    }
}
