/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test3;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvFileSource;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @ParameterizedTest
    @DisplayName("弱一般等价类测试")
    @CsvFileSource(resources="/test1.csv")
    void fileTest1(String fromtime,String totime,String expected){
        App phoneFee=new App();
        assertEquals(expected,phoneFee.cost(fromtime,totime));
    }

    @ParameterizedTest
    @DisplayName("强一般等价类测试")
    @CsvFileSource(resources="/test2.csv")
    void fileTest2(String fromtime,String totime,String expected){
        App phoneFee=new App();
        assertEquals(expected,phoneFee.cost(fromtime,totime));
    }
}
