/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @ParameterizedTest
    @CsvSource({
            "1,2,3,非三角形",
            "-1,2,3,输入错误"
    })
    void testWithCsvSource(int a,int b,int c,String expected) {
        App triangle = new App();
        assertEquals(expected, triangle.classify(a,b,c));
    }
    @ParameterizedTest
    @CsvFileSource(resources = "/test1.csv")
    void test_csv_file_source(int a, int b, int c, String expected) {
        assertEquals(expected, triangle.classify(a,b,c));
    }
}
