/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test4;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

public class test4 {
    public static String GetMoney(String time1, String time2) {

        try {
            SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            Date date1 = format1.parse(time1);
            Date date2 = format1.parse(time2);
            Calendar cal1 = Calendar.getInstance();
            cal1.setTime(date1);
            Calendar cal2 = Calendar.getInstance();
            cal2.setTime(date2);
            long phonetime = cal2.getTime().getTime() - cal1.getTime().getTime();
            long minute;
            //通话时长计算
            if (phonetime >= 0 && phonetime / 1000 < 60 || phonetime % 60000 > 0)
                minute = phonetime / 1000 / 60 + 1;
            else
                minute = phonetime / 1000 / 60;
            //判断时间
            if (cal1.get(Calendar.MONTH) == Calendar.NOVEMBER && cal1.get(Calendar.DATE) <= 7 && cal1.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY) {
                //秋令时 -- 开始时间在十一月第一个星期日
                if (cal1.get(Calendar.HOUR_OF_DAY) == 2 && cal2.get(Calendar.HOUR_OF_DAY) == 2 && cal2.get(Calendar.HOUR_OF_DAY) < 3 && cal2.get(Calendar.MINUTE) <= cal1.get(Calendar.MINUTE)) {
                    //因为转换而出现通话时间为负的情况
                    minute += 60;
                    return Money(minute);
                } else if (cal1.get(Calendar.HOUR_OF_DAY) < 2 && cal2.get(Calendar.HOUR_OF_DAY) >= 2) {
                    //开始时间是两点前，结束时间是两点后（经历第二次转换
                    return Money(minute + 60);
                } else {
                    return Money(minute);
                }

            } else {
                //秋令时 -- 结束时间在十一月第一个星期日
                if (cal2.get(Calendar.MONTH) == Calendar.NOVEMBER && cal2.get(Calendar.DATE) <= 7 && cal2.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY) {
                    if (cal2.get(Calendar.HOUR_OF_DAY) >= 2)
                        minute += 60;
                }
                //夏令时 -- 2023年 三月夏令时为3月12号，因为每年不确定，这里做特判
                else {
                    //开始时间为3月12星期日
                    if ((cal1.get(Calendar.MONTH) == Calendar.MARCH && cal1.get(Calendar.DATE) == 12 && cal1.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY)) {
                        if (cal1.get(Calendar.HOUR_OF_DAY) <= 2 && cal2.get(Calendar.HOUR_OF_DAY) >= 3)
                            //开始时间在两点前，结束时间在三点后（经过了第一次转换
                            minute -= 60;
                    } else {//开始时间不在夏令时
                        if ((cal2.get(Calendar.MONTH) == Calendar.MARCH && cal2.get(Calendar.DATE) == 12 && cal2.get(Calendar.DAY_OF_WEEK) == Calendar.SUNDAY)) {
                            //但是结束时间在（从前一天打到这一天
                            if (cal2.get(Calendar.HOUR_OF_DAY) >= 3)
                                minute -= 60;
                        }
                    }
                }
                return Money(minute);
            }

        } catch (ParseException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
            return "-1";
        }
    }


    public static String Money(long minute){
        //收费函数
        double money = 0;
        //没有超过30个小时的通话
        if (minute > 1800 || minute <= 0) {
            return String.valueOf(String.format("%.2f", money));
        } else {
            if (minute <= 20)
                money = minute * 0.05;
            else
                money = 1 + (minute - 20) * 0.1;
        }
        return String.valueOf(String.format("%.2f", money));
    }
}
